# Generated by Django 3.2.13 on 2023-09-05 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayapproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='День')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('approver', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ПодтвердившийВ', to=settings.AUTH_USER_MODEL, verbose_name='ПодтвердившийВ')),
                ('per', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ТабельВ', to='reference.driver', verbose_name='ТабельВ')),
            ],
            options={
                'verbose_name': 'Проверка дня',
                'verbose_name_plural': 'Проверки дней',
            },
        ),
    ]
