# Generated by Django 3.2.13 on 2023-09-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_dayapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='grade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Разряд'),
        ),
    ]
