# Generated by Django 3.2.13 on 2023-09-10 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_persone_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='owner',
            field=models.CharField(default='ООО "ПМК"', max_length=125, verbose_name='Собственник'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 9, 20), verbose_name='Срок до'),
        ),
    ]
