# Generated by Django 3.2.13 on 2023-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20230910_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='da1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 1 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 10 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 11 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 12 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 13 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 14 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 15 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 16 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 17 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 18 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 19 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 2 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 20 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da21',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 21 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da22',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 22 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da23',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 23 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 24 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 25 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da26',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 26 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da27',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 27 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da28',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 28 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da29',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 29 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 3 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da30',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 30 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da31',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 31 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 4 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 5 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 6 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 7 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 8 дня'),
        ),
        migrations.AddField(
            model_name='driver',
            name='da9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 9 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 1 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 10 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 11 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 12 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 13 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 14 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 15 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 16 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 17 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 18 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 19 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 2 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 20 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da21',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 21 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da22',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 22 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da23',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 23 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 24 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 25 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da26',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 26 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da27',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 27 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da28',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 28 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da29',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 29 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 3 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da30',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 30 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da31',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 31 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 4 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 5 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 6 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 7 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 8 дня'),
        ),
        migrations.AddField(
            model_name='period',
            name='da9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверка 9 дня'),
        ),
    ]
