# Generated by Django 3.2.13 on 2023-09-10 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20230910_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 9, 21), verbose_name='Срок до'),
        ),
    ]
