# Generated by Django 3.2.13 on 2023-09-14 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_alter_task_body_need_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_list',
            name='used',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Использованно выходных'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 9, 24), verbose_name='Срок до'),
        ),
    ]
