# Generated by Django 3.2.13 on 2023-09-15 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_auto_20230914_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_list',
            name='output',
            field=models.IntegerField(default=1, verbose_name='Выходные'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 9, 25), verbose_name='Срок до'),
        ),
    ]
