# Generated by Django 3.2.13 on 2023-09-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_auto_20230915_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_list',
            name='output',
            field=models.IntegerField(default=1, max_length=1, verbose_name='Выходные'),
        ),
    ]
