# Generated by Django 3.2.13 on 2023-09-19 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_alter_driver_list_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='number',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Комментарий'), max_length=125, null=True, verbose_name='Гос. номер'),
        ),
        migrations.AddField(
            model_name='persone',
            name='work_hours',
            field=models.CharField(default=10, max_length=55, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 9, 29), verbose_name='Срок до'),
        ),
    ]
