# Generated by Django 3.2.13 on 2023-09-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20230919_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='number',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Гос. номер'),
        ),
    ]
