# Generated by Django 3.2.13 on 2023-09-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_alter_automobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_list',
            name='auto_block',
            field=models.IntegerField(blank=True, null=True, verbose_name='Блокировка Т\\С'),
        ),
    ]
