# Generated by Django 3.2.13 on 2023-09-19 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0012_driver_list_auto_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='objs',
            name='prorab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Прораб', to=settings.AUTH_USER_MODEL, verbose_name='Прораб'),
        ),
    ]
