# Generated by Django 3.2.13 on 2023-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0014_auto_20230925_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='salary',
            field=models.FloatField(default=0, max_length=9, verbose_name='Оклад'),
        ),
    ]
