# Generated by Django 3.2.13 on 2023-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0015_alter_persone_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='driver',
            field=models.IntegerField(default=0, verbose_name='Уволен?'),
        ),
    ]
