# Generated by Django 3.2.13 on 2023-09-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_alter_persone_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='phone_number',
            field=models.CharField(default='+7...', max_length=17, verbose_name='Номер телефона'),
        ),
    ]
