# Generated by Django 3.2.13 on 2023-09-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_persone_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='workgroup',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Отдел'),
        ),
    ]
