# Generated by Django 3.2.13 on 2023-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0018_persone_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='leaved',
            field=models.IntegerField(default=0, verbose_name='Уволен?'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='driver',
            field=models.IntegerField(choices=[(1, 'Водитель'), (0, 'Сотрудник')], default=0, verbose_name='Водитель?'),
        ),
    ]
