# Generated by Django 3.2.13 on 2023-09-26 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0019_auto_20230925_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabel_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('comment', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Группа табелей',
                'verbose_name_plural': 'Группы табелей',
            },
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 10, 6), verbose_name='Срок до'),
        ),
    ]
