# Generated by Django 3.2.13 on 2023-09-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_auto_20230926_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel_group',
            name='name',
        ),
        migrations.AddField(
            model_name='tabel_group',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Период группы'),
        ),
    ]
