# Generated by Django 3.2.13 on 2023-09-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0021_auto_20230926_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Группа', to='reference.tabel_group', verbose_name='Группа табелей персонала'),
        ),
    ]
