# Generated by Django 3.2.13 on 2023-10-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0022_period_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabel_group',
            options={'ordering': ['-date'], 'verbose_name': 'Группа табелей', 'verbose_name_plural': 'Группы табелей'},
        ),
        migrations.AlterField(
            model_name='persone',
            name='date_accept',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='date_leave',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2023, 10, 17), verbose_name='Срок до'),
        ),
    ]
