# Generated by Django 3.2.13 on 2023-12-30 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0023_auto_20231007_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_list',
            name='output',
            field=models.IntegerField(blank=True, default=1, max_length=1, null=True, verbose_name='Выходные'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2024, 1, 9), verbose_name='Срок до'),
        ),
    ]
