# Generated by Django 3.2.13 on 2024-02-08 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0024_auto_20231230_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='graphic',
            field=models.IntegerField(choices=[(1, 'Вахта'), (2, '5/7'), (3, '6/7'), (4, '2/2'), (5, '7')], default='1', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2024, 2, 18), verbose_name='Срок до'),
        ),
        migrations.AlterField(
            model_name='task_head',
            name='status',
            field=models.CharField(blank=True, choices=[('На рассмотрение', 'На рассмотрение'), ('Одобрен', 'Одобрен'), ('Отклонен', 'Отклонен')], default='На рассмотрение', max_length=55, null=True, verbose_name='Статус'),
        ),
    ]
