# Generated by Django 3.2.13 on 2024-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0025_auto_20240208_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_list',
            name='output',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Выходные'),
        ),
    ]
