# Generated by Django 3.2.13 on 2024-02-09 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0026_alter_tabel_list_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='snils',
            field=models.CharField(default='', max_length=16, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2024, 2, 19), verbose_name='Срок до'),
        ),
    ]
