# Generated by Django 3.2.13 on 2024-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0027_auto_20240209_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='phone_number',
            field=models.CharField(default='', max_length=17, verbose_name='Номер телефона'),
        ),
    ]
