# Generated by Django 3.2.13 on 2024-02-13 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0028_alter_persone_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='company',
            field=models.IntegerField(choices=[(1, 'ПМК'), (2, 'Неоформ')], default=1, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='driver',
            field=models.IntegerField(choices=[(1, 'Водитель'), (0, 'Нет')], default=0, verbose_name='Водитель?'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='position',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='snils',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2024, 2, 23), verbose_name='Срок до'),
        ),
        migrations.CreateModel(
            name='driver_tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0, verbose_name='Тариф')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.persone', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Тариф сотрудника',
                'verbose_name_plural': 'Тарифы сотрудников',
            },
        ),
    ]
