# Generated by Django 3.2.13 on 2024-02-14 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0029_auto_20240213_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='company',
            field=models.IntegerField(blank=True, choices=[(1, 'ПМК'), (2, 'Неоформ')], null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='graphic',
            field=models.IntegerField(blank=True, choices=[(1, 'Вахта'), (2, '5/7'), (3, '6/7'), (4, '2/2'), (5, '7')], default='1', null=True, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=17, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='salary',
            field=models.FloatField(blank=True, default=0, max_length=9, null=True, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='work_hours',
            field=models.CharField(blank=True, default=10, max_length=55, null=True, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(default=datetime.date(2024, 2, 24), verbose_name='Срок до'),
        ),
    ]
