# Generated by Django 3.2.13 on 2024-02-14 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0030_auto_20240214_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persone',
            name='snils',
            field=models.CharField(default='', max_length=16, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 25), null=True, verbose_name='Срок до'),
        ),
    ]
