# Generated by Django 3.2.13 on 2024-02-20 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0031_auto_20240215_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_body',
            name='ci',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 1), null=True, verbose_name='Срок до'),
        ),
    ]
