# Generated by Django 3.2.13 on 2024-02-27 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0032_auto_20240220_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 9), null=True, verbose_name='Срок до'),
        ),
    ]
