# Generated by Django 3.2.13 on 2024-02-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0033_alter_task_body_need_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='idea',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Заметки'),
        ),
    ]
