# Generated by Django 3.2.13 on 2024-03-11 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0034_persone_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 21), null=True, verbose_name='Срок до'),
        ),
        migrations.CreateModel(
            name='persone_salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 3, 11), verbose_name='Дата')),
                ('salary', models.FloatField(blank=True, default=0, null=True, verbose_name='Оклад')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий')),
                ('persone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.persone', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Оклад',
                'verbose_name_plural': 'Оклады',
            },
        ),
    ]
