# Generated by Django 3.2.13 on 2024-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0035_auto_20240311_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persone_salary',
            options={'verbose_name': 'Оклад и разряд', 'verbose_name_plural': 'Оклады и разряды'},
        ),
        migrations.AddField(
            model_name='persone_salary',
            name='grade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Разряд'),
        ),
    ]
