# Generated by Django 3.2.13 on 2024-03-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0036_auto_20240311_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone_salary',
            name='tax',
            field=models.FloatField(default=0, verbose_name='Тариф'),
        ),
    ]
