# Generated by Django 3.2.13 on 2024-03-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0037_persone_salary_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persone_salary',
            name='tax',
        ),
    ]
