# Generated by Django 3.2.13 on 2024-03-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0038_remove_persone_salary_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver_tax',
            options={'verbose_name': 'Тариф водителя', 'verbose_name_plural': 'Тарифы водителей'},
        ),
        migrations.CreateModel(
            name='driver_tax_lagacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField(default=0, verbose_name='Тариф')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.persone', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Тариф водителя старые',
                'verbose_name_plural': 'Тарифы водителей старые ',
            },
        ),
    ]
