# Generated by Django 3.2.13 on 2024-03-15 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0039_auto_20240311_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='sum_method',
            field=models.IntegerField(default=0, max_length=1, verbose_name='Метод расчета'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 15), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 25), null=True, verbose_name='Срок до'),
        ),
    ]
