# Generated by Django 3.2.13 on 2024-03-20 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0040_auto_20240315_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=2000, verbose_name='Уведомления')),
                ('date', models.DateField(default=datetime.date(2024, 3, 20), verbose_name='Дата уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 20), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 30), null=True, verbose_name='Срок до'),
        ),
        migrations.CreateModel(
            name='notificated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificated', models.IntegerField(default=0, verbose_name='Оповещен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificater', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оповещение для пользователя',
                'verbose_name_plural': 'Оповещения для пользователей',
            },
        ),
    ]
