# Generated by Django 3.2.13 on 2024-03-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0041_auto_20240320_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование уведомления'),
        ),
    ]
