# Generated by Django 3.2.13 on 2024-04-06 23:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0042_notifications_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_body',
            name='status_changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Изменивший', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен'),
        ),
        migrations.AddField(
            model_name='task_head',
            name='id_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='task_head',
            name='system',
            field=models.CharField(blank=True, default=' ', max_length=5650, null=True, verbose_name='Системная информация'),
        ),
        migrations.AddField(
            model_name='task_head',
            name='type',
            field=models.CharField(blank=True, choices=[('Наличные', 'Наличные'), ('Проектные ', 'Проектные '), ('Расходники ', 'Расходники '), ('Прочие', 'Прочие')], max_length=50, null=True, verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 7), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 7), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 17), null=True, verbose_name='Срок до'),
        ),
    ]
