# Generated by Django 3.2.13 on 2024-04-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0043_auto_20240407_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('obj', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.objs', verbose_name='Объект')),
            ],
        ),
    ]
