# Generated by Django 3.2.13 on 2024-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0044_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_number',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Номер'),
        ),
    ]
