# Generated by Django 3.2.13 on 2024-04-12 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0045_alter_task_number_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 12), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 12), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 22), null=True, verbose_name='Срок до'),
        ),
        migrations.CreateModel(
            name='gazolin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0, max_length=9, verbose_name='Остаток топлива')),
                ('obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.objs', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Остаток топлива',
                'verbose_name_plural': 'Остатки топлива',
            },
        ),
        migrations.CreateModel(
            name='gaz_tabel_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 4, 12), verbose_name='Период табеля')),
                ('dw1', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw2', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw3', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw4', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw5', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw6', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw7', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw8', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw9', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw10', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw11', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw12', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw13', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw14', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw15', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw16', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw17', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw18', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw19', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw20', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw21', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw22', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw23', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw24', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw25', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw26', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw27', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw28', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw29', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw30', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('dw31', models.DateField(blank=True, max_length=5, null=True, verbose_name='День недели')),
                ('gaz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.gazolin', verbose_name='Топливный объект')),
            ],
            options={
                'verbose_name': 'Табель топлива',
                'verbose_name_plural': 'Табели топлива',
            },
        ),
        migrations.CreateModel(
            name='gaz_tabel_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d2', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d3', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d4', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d5', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d6', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d7', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d8', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d9', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d10', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d11', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d12', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d13', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d14', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d15', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d16', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d17', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d18', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d19', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d20', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d21', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d22', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d23', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d24', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d25', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d26', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d27', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d28', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d29', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d30', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('d31', models.CharField(blank=True, max_length=5, null=True, verbose_name='День')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.automobile', verbose_name='Т\\С')),
                ('persone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.persone', verbose_name='Сотрудник')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.gaz_tabel_head', verbose_name='Табель топлива')),
            ],
            options={
                'verbose_name': 'Табель топлива',
                'verbose_name_plural': 'Табели топлива',
            },
        ),
        migrations.CreateModel(
            name='gaz_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaz_add', models.FloatField(default=0, max_length=9, verbose_name='Количество')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 12, 23, 37, 5, 971942), verbose_name='Время прихода')),
                ('gaz_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.gazolin', verbose_name='Объект прихода')),
            ],
            options={
                'verbose_name': 'Приход топлива',
                'verbose_name_plural': 'Приходы топлива',
            },
        ),
    ]
