# Generated by Django 3.2.13 on 2024-04-20 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0046_auto_20240412_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 13, 54, 57, 166083), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 1'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d10',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 10'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d11',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 11'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d12',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 12'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d13',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 13'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d14',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 14'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d15',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 15'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d16',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 16'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d17',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 17'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d18',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 18'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d19',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 19'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 2'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d20',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 20'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d21',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 21'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d22',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 22'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d23',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 23'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d24',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 24'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d25',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 25'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d26',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 26'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d27',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 27'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d28',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 28'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d29',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 29'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 3'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d30',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 30'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d31',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 31'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d4',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 4'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d5',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 5'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d6',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 6'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d7',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 7'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d8',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 8'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_body',
            name='d9',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='День 9'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 20), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 20), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 20), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 30), null=True, verbose_name='Срок до'),
        ),
        migrations.AlterField(
            model_name='task_head',
            name='type',
            field=models.CharField(blank=True, choices=[('Наличные', 'Наличные'), ('Проектные ', 'Проектные '), ('Расходники ', 'Расходники '), ('Прочие', 'Прочие')], default='Прочие', max_length=50, null=True, verbose_name='Вид заявки'),
        ),
    ]
