# Generated by Django 3.2.13 on 2024-04-21 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0047_auto_20240420_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_list',
            name='daypicker1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d1', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 1 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d10', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 10 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d11', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 11 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d12', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 12 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d13', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 13 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d14', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 14 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d15', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 15 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d16', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 16 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d17', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 17 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d18', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 18 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d19', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 19 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d2', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 2 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d20', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 20 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d21', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 21 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d22', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 22 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d23', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 23 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d24', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 24 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d25', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 25 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d26', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 26 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d27', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 27 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d28', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 28 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d29', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 29 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d3', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 3 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d30', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 30 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d31', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 31 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d4', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 4 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d5', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 5 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d6', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 6 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d7', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 7 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d8', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 8 дня'),
        ),
        migrations.AddField(
            model_name='driver_list',
            name='daypicker9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d9', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 9 дня'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 17, 18, 52, 202748), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 21), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 21), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 21), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 1), null=True, verbose_name='Срок до'),
        ),
    ]
