# Generated by Django 3.2.13 on 2024-04-21 14:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0048_auto_20240421_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt1', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 1 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt10', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 10 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt11', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 11 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt12', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 12 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt13', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 13 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt14', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 14 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt15', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 15 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt16', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 16 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt17', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 17 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt18', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 18 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt19', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 19 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt2', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 2 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt20', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 20 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt21', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 21 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt22', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 22 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt23', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 23 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt24', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 24 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt25', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 25 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt26', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 26 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt27', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 27 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt28', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 28 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt29', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 29 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt3', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 3 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt30', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 30 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt31', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 31 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt4', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 4 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt5', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 5 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt6', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 6 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt7', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 7 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt8', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 8 дня'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='daypicker9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dt9', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил 9 дня'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 17, 38, 13, 959413), verbose_name='Время прихода'),
        ),
    ]
