# Generated by Django 3.2.13 on 2024-04-21 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0049_auto_20240421_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaz_tabel_body',
            options={'verbose_name': 'Список в табеле топлива', 'verbose_name_plural': 'Списки в табелях топлива'},
        ),
        migrations.AddField(
            model_name='persone',
            name='resident',
            field=models.CharField(blank=True, choices=[('РФ', 'РФ'), ('Иностранец', 'Иностранец')], max_length=15, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 23, 54, 1, 531319), verbose_name='Время прихода'),
        ),
    ]
