# Generated by Django 3.2.13 on 2024-04-21 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0050_auto_20240421_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaz_tabel_body',
            name='company',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='gaz_tabel_body',
            name='full_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='gaz_tabel_body',
            name='position',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 0, 41, 29, 529699), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 22), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 22), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 22), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 2), null=True, verbose_name='Срок до'),
        ),
    ]
