# Generated by Django 3.2.13 on 2024-04-28 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0051_auto_20240422_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 2, 52, 3, 806934), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 29), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 29), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='sum_method',
            field=models.IntegerField(default=0, max_length=15, verbose_name='Метод расчета'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 29), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 9), null=True, verbose_name='Срок до'),
        ),
    ]
