# Generated by Django 3.2.13 on 2024-04-28 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0052_auto_20240429_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 2, 55, 7, 291621), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='sum_method',
            field=models.IntegerField(default=0, max_length=1, verbose_name='Метод расчета'),
        ),
    ]
