# Generated by Django 3.2.13 on 2024-04-28 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0053_auto_20240429_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 2, 55, 52, 768543), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='resident',
            field=models.CharField(blank=True, choices=[('РФ', 'РФ'), ('Иностранец', 'Иностранец')], max_length=50, null=True, verbose_name='Гражданство'),
        ),
    ]
