# Generated by Django 3.2.13 on 2024-05-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0054_auto_20240429_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='workdays2',
            field=models.IntegerField(blank=True, default=15, verbose_name='Количество рабочих дней графика 2/2'),
        ),
        migrations.AddField(
            model_name='period',
            name='workdays5',
            field=models.IntegerField(blank=True, default=22, verbose_name='Количество рабочих дней графика 5/2'),
        ),
        migrations.AddField(
            model_name='period',
            name='workdays6',
            field=models.IntegerField(blank=True, default=26, verbose_name='Количество рабочих дней графика 6/1'),
        ),
        migrations.AddField(
            model_name='tabel_list',
            name='graphic',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 17, 55, 45, 142962), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 10), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 10), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='period',
            name='workdays',
            field=models.IntegerField(blank=True, default=30, verbose_name='Количество рабочих дней'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 10), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 20), null=True, verbose_name='Срок до'),
        ),
    ]
