# Generated by Django 3.2.13 on 2024-05-11 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0055_auto_20240510_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='workdays2',
        ),
        migrations.RemoveField(
            model_name='period',
            name='workdays6',
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 14, 21, 24, 397173), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 11), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 11), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 11), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 21), null=True, verbose_name='Срок до'),
        ),
    ]
