# Generated by Django 3.2.13 on 2024-05-13 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0056_auto_20240511_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='exception',
            field=models.IntegerField(default=0, max_length=1, verbose_name='Исключение'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 6, 3, 10, 267064), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 23), null=True, verbose_name='Срок до'),
        ),
    ]
