# Generated by Django 3.2.13 on 2024-06-12 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0058_auto_20240612_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaz_tabel_head',
            name='gaz_minus',
            field=models.FloatField(default=0, max_length=9, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='gazolin',
            name='gaz_sum',
            field=models.FloatField(default=0, max_length=9, verbose_name='Остаток объекта'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 13, 9, 3, 782174), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gazolin',
            name='sum',
            field=models.FloatField(default=0, max_length=9, verbose_name='Топливо принятое в сумме'),
        ),
    ]
