# Generated by Django 3.2.13 on 2024-06-12 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0059_auto_20240612_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaz_tabel_body',
            name='sum',
            field=models.FloatField(default=0, max_length=55, verbose_name='Суммарный расход'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 15, 38, 43, 859832), verbose_name='Время прихода'),
        ),
    ]
