# Generated by Django 3.2.13 on 2024-09-02 04:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0060_auto_20240612_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='objs',
            name='watch1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Наблюдатель1', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатель1'),
        ),
        migrations.AddField(
            model_name='objs',
            name='watch2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Наблюдатель2', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатель2'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 7, 48, 42, 234867), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 2), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 2), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 2), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 12), null=True, verbose_name='Срок до'),
        ),
    ]
