# Generated by Django 3.2.13 on 2024-11-16 22:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0061_auto_20240902_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_head',
            name='control',
            field=models.CharField(blank=True, choices=[('Не пройден', 'Не пройден'), ('Пройден', 'Пройден')], default='Не пройден', max_length=55, null=True, verbose_name='Контроль'),
        ),
        migrations.AddField(
            model_name='task_head',
            name='control_changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Проверяющий', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 1, 52, 0, 651795), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 17), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 17), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 17), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 27), null=True, verbose_name='Срок до'),
        ),
    ]
