# Generated by Django 3.2.13 on 2024-11-16 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0062_auto_20241117_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 1, 52, 23, 585669), verbose_name='Время прихода'),
        ),
    ]
