# Generated by Django 3.2.13 on 2024-11-17 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0063_alter_gaz_input_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_head_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jff', models.CharField(default='jff', max_length=10, verbose_name='jff')),
            ],
            options={
                'verbose_name': 'Контроль заявки',
                'verbose_name_plural': 'Контроль Заявок',
            },
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 23, 28, 0, 373364), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='task_head',
            name='control',
            field=models.CharField(blank=True, choices=[('Не пройден', 'Не пройден'), ('Пройден', 'Пройден'), ('На редактирование', 'На редактирование')], default='Не пройден', max_length=55, null=True, verbose_name='Контроль'),
        ),
    ]
