# Generated by Django 3.2.13 on 2025-03-27 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0064_auto_20241117_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='education',
            field=models.CharField(blank=True, max_length=152, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='gaz_input',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 7, 46, 39, 323660), verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='gaz_tabel_head',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 27), verbose_name='Период табеля'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 27), verbose_name='Дата уведомления'),
        ),
        migrations.AlterField(
            model_name='persone_salary',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 27), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task_body',
            name='need_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 6), null=True, verbose_name='Срок до'),
        ),
    ]
